name: Run pipeline and deploy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  run-pipeline-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        shell: bash

      - name: Run script
        run: yarn run-data-pipeline
        shell: bash

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "c998444368535e9100cd4e83bb76fb41"
          projectName: "salary-snapshot"
          directory: "public"
          wranglerVersion: "3"
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
